# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-07 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumagis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='user_id',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
