# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-13 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumagis', '0002_line_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='informacion_usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('apellido', models.CharField(max_length=250)),
                ('foto', models.ImageField(upload_to=b'photos/')),
            ],
        ),
        migrations.CreateModel(
            name='status_usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='line',
            name='guardar',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
