# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumagis', '0003_auto_20161017_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='shortest_path',
            field=models.CharField(default=b'', max_length=50000),
        ),
    ]
