# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pumagis', '0006_line'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='line',
            options={'verbose_name': 'Line'},
        ),
    ]
