# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 20:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pumagis', '0007_auto_20161017_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='shortest_path',
        ),
    ]
