# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumagis', '0002_auto_20161017_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
