# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-02 03:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pumagis', '0010_auto_20161026_2319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='line',
            options={'verbose_name': 'Line', 'verbose_name_plural': 'Lines'},
        ),
        migrations.AlterModelOptions(
            name='point',
            options={'verbose_name': 'Point', 'verbose_name_plural': 'Points'},
        ),
    ]
