# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-03 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumagis', '0011_auto_20161202_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='_shortest_path',
            field=models.TextField(default=b''),
        ),
    ]
