# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-03 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumagis', '0014_line__shortest_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='tipo_transporte',
            field=models.CharField(default=b'', max_length=50),
        ),
    ]
