# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-03 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumagis', '0015_line_tipo_transporte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='_shortest_path',
        ),
        migrations.AddField(
            model_name='line',
            name='camino_mas_corto',
            field=models.TextField(default=b''),
        ),
    ]
