# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-03 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumagis', '0016_auto_20161203_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='camino_mas_corto',
            field=models.CharField(default=b'', max_length=250),
        ),
    ]
