# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_origen', models.CharField(default=b'(0.0,0.0)', max_length=50)),
                ('p_destino', models.CharField(default=b'(0.0,0.0)', max_length=50)),
            ],
            options={
                'verbose_name': 'Line',
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.FloatField(default=0.0)),
                ('lat', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Point',
            },
        ),
    ]
